image: dockerbuildagent/buildbase:buster
manifests:
  - image: dockerbuildagent/buildbase:buster-amd64
    platform:
      architecture: amd64
      os: linux
  - image: dockerbuildagent/buildbase:buster-arm32v7
    platform:
      architecture: arm
      os: linux
      variant: v7
  - image: dockerbuildagent/buildbase:buster-arm64v8
    platform:
      architecture: arm64
      os: linux
      variant: v8
